const { modelPrinter } = require("./modelPrinter")
const impresorasFinancieraAlmacen = [
    {
        serial: '5004028933',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5004101147',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605276715',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605273341',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605276525',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605274300',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605272930',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605276524',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605103835',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605269773',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5004033662',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5004101542',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5001069750',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5004101121',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605274461',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5004095077',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605273600',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605209372',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915+')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605008127',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605270124',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605272933',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    {
        serial: '5605270116',
        activo: null,
        statusId: 2,
        categoryId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].categoryId,
        modelId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].id,
        brandId: modelPrinter.filter(printer => printer.name === 'HighPrint 4915xe')[0].brandId,
        employeeId: null,
        locationId: 24080915,
    },
    
]
module.exports = { impresorasFinancieraAlmacen }