const { almacenes: locations, almacenName } = require("../location/locations")
const { modelBAM } = require("../modelsSeries/modelBram")

const partsAndPieces = [
    {
        serial: '087D1006806',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '087D1006803',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '087D1006822',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '087D1006672',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'USB TL-WN821N')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007340928',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '860279030082993',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'D32')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'D32')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'D32')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '911563808510569',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'JMR451')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'JMR451')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'JMR451')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '352015100140732',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF180')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF180')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF180')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '352015100140807',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF181')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF181')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF181')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '865461020128151',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF910')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF910')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF910')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: null,
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF911')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF911')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF911')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861376036886317',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920V ')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920V ')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920V ')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032637157',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035753385',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '911563801209466',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'JMR451')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'JMR451')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'JMR451')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032644450',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032654871',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032640383',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032631200',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032614651',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032643627',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032641977',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032643775',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '861887032646356',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MF920VS')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007344177',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007341280',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007343617',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007340944',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008968933',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007342932',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007346180',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007349341',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007342957',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008969808',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007341702',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007343377',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008969329',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007347345',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008967232',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008969881',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008968313',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007341652',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007348681',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007343583',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007341637',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007350448',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007349374',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007348087',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828008969501',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007350265',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007341140',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '014828007349069',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'MW41NF')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035748781',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '86663740355753617',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032908958',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035745670',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035758665',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035738469',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035760851',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035760240',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032892251',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035765355',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035742297',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035767906',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032901136',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032912463',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035762972',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035745795',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032906879',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035749730',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035763517',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032910186',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032900914',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035765033',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032906267',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035743337',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035743535',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035748385',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035758657',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035759010',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035765371',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374035760588',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032906127',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '866374035763541',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4 ')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4 ')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4 ')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8666374032909717',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'R4 ')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'R4 ')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'R4 ')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8CU94709DW',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Cable USB')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Cable USB')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Cable USB')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8CU94706SB',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Cable USB')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Cable USB')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Cable USB')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '384097900105',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'FaceCam 321')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'FaceCam 321')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'FaceCam 321')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'YB208C201937',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'FaceCam 1010')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'FaceCam 1010')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'FaceCam 1010')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'WR7FB03726R',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'DMC-LS70')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'DMC-LS70')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'DMC-LS70')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8094C9BC100073X',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8094C9BC10006SM',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '8094C9BC10005RV',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'ST65')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '164455',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'SteadyShot DSC-W620')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'SteadyShot DSC-W620')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'SteadyShot DSC-W620')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '164599',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'SteadyShot DSC-W620')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'SteadyShot DSC-W620')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'SteadyShot DSC-W620')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'A1AP15G00125',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Tandberg TTC8-03')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Tandberg TTC8-03')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Tandberg TTC8-03')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'A1AP48F00259',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Tandberg TTC8-03')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Tandberg TTC8-03')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Tandberg TTC8-03')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'F6QMW06GF4YH',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Air A1475')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Air A1475')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Air A1475')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '908614392507',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'USB Wireless 850')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'USB Wireless 850')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'USB Wireless 850')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '31913/61Q301635',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '356721054192043',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Asha 311')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Asha 311')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Asha 311')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'C6KD10R1N72Y',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '359243069673906',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'R28H62JW4JM',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Samsung Galaxy J2')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Samsung Galaxy J2')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Samsung Galaxy J2')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '32D35527FAJ',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'V265')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'V265')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'V265')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '356506040130417',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'WX306')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'WX306')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'WX306')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '865371027220705',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Y220')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Y220')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Y220')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'DNPCW6ZTN72Y',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'C6KD177LN72Y',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 11')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '359320060122842',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '359248069830158',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1524')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '359318060346700',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1525')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1525')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1525')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '359248069830315',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1526')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1526')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Iphone 6 A1526')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '31913/61Q300917',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '31913/61Q206868',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '31913/61Q301677',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Redmi Note 10 Onyx Gray')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'DV01GRT',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Convertidor de VGA - HDMI')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Convertidor de VGA - HDMI')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Convertidor de VGA - HDMI')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'DV01GSK',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Convertidor de VGA - HDMI')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Convertidor de VGA - HDMI')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Convertidor de VGA - HDMI')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'WP120QC00968',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'SP-i170')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'SP-i170')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'SP-i170')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'THY02006MQ',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'HSA-Q001PR')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'HSA-Q001PR')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'HSA-Q001PR')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'UP602AYB',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'DK1522')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'DK1522')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'DK1522')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '5CG039WDVW',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'USB-C Dock G5')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'USB-C Dock G5')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'USB-C Dock G5')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '1CW8172430',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'HSA-Q001PR')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'HSA-Q001PR')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'HSA-Q001PR')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: 'UP500G6T',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'DK1522')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'DK1522')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'DK1522')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: null,
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Active Pen G2')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Active Pen G2')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Active Pen G2')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: null,
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Y1215P')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Y1215P')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Y1215P')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '9CP92505JW',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Elite')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Elite')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Elite')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
    {
        serial: '905901080114',
        activo: null,
        statusId: 2,
        categoryId: modelBAM.filter(keyboard => keyboard.name === 'Wireless 900 Model 1737')[0].categoryId,
        modelId: modelBAM.filter(keyboard => keyboard.name === 'Wireless 900 Model 1737')[0].id,
        brandId: modelBAM.filter(keyboard => keyboard.name === 'Wireless 900 Model 1737')[0].brandId,
        employeeId: null,
        locationId: locations.filter(location => location.name === almacenName.TORREBNC5DEJULIOALMACENPISO1)[0].id,
        observation: ''
    },
]

module.exports = { partsAndPieces }