const states = require("./state")

const cities = [  
    { name: 'Anaco', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'Barcelona', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'El Tigre', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'El Tigrito', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'Lecherias', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'Puerto la Cruz', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'Píritu', stateId: states.filter(state => state.name === 'Anzoátegui')[0].id },
    { name: 'San Fernando de Apure', stateId: states.filter(state => state.name === 'Apure')[0].id },
    { name: 'Cagua', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'Choroní', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'La Victoria', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'Maracay', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'Palo Negro', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'San Sebastián', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'Turmero', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'Villa de Cura', stateId: states.filter(state => state.name === 'Aragua')[0].id },
    { name: 'Barinas', stateId: states.filter(state => state.name === 'Barinas')[0].id },
    { name: 'Ciudad Bolívar', stateId: states.filter(state => state.name === 'Bolívar')[0].id },
    { name: 'Puerto Ordaz', stateId: states.filter(state => state.name === 'Bolívar')[0].id },
    { name: 'San Feliz', stateId: states.filter(state => state.name === 'Bolívar')[0].id },
    { name: 'Unare', stateId: states.filter(state => state.name === 'Bolívar')[0].id },
    { name: 'Bejuma', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Guacara', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Los Guayos', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Montalbán', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Naguanagua', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Puerto Cabello', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'San Diego', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Tocuyito', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'Valencia', stateId: states.filter(state => state.name === 'Carabobo')[0].id },
    { name: 'San Carlos', stateId: states.filter(state => state.name === 'Cojedes')[0].id },
    { name: 'Tinaquillo', stateId: states.filter(state => state.name === 'Cojedes')[0].id },
    { name: 'Casacoima', stateId: states.filter(state => state.name === 'Delta Amacuro')[0].id },
    { name: 'Tucupita', stateId: states.filter(state => state.name === 'Delta Amacuro')[0].id },
    { name: 'Caracas', stateId: states.filter(state => state.name === 'Distrito Capital')[0].id },
    { name: 'Coro', stateId: states.filter(state => state.name === 'Falcón')[0].id },
    { name: 'Dabajuro', stateId: states.filter(state => state.name === 'Falcón')[0].id },
    { name: 'Punto FIjo', stateId: states.filter(state => state.name === 'Falcón')[0].id },
    { name: 'Calabozo', stateId: states.filter(state => state.name === 'Guárico')[0].id },
    { name: 'El Sombrero', stateId: states.filter(state => state.name === 'Guárico')[0].id },
    { name: 'San Juan de los Morros', stateId: states.filter(state => state.name === 'Guárico')[0].id },
    { name: 'Tucupido', stateId: states.filter(state => state.name === 'Guárico')[0].id },
    { name: 'Valle de la Pascua', stateId: states.filter(state => state.name === 'Guárico')[0].id },
    { name: 'Barquisimeto', stateId: states.filter(state => state.name === 'Lara')[0].id },
    { name: 'Cabudare', stateId: states.filter(state => state.name === 'Lara')[0].id },
    { name: 'Carora', stateId: states.filter(state => state.name === 'Lara')[0].id },
    { name: 'Quíbor', stateId: states.filter(state => state.name === 'Lara')[0].id },
    { name: 'El Vigía', stateId: states.filter(state => state.name === 'Mérida')[0].id },
    { name: 'Mérida', stateId: states.filter(state => state.name === 'Mérida')[0].id },
    { name: 'Caracas', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Carrizales', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Caucagua', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Charavalle', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Guarenas', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Guatire', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Los Teques', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'San Antonio de los Altes', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'San José de Rio Chico', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Santa Teresa', stateId: states.filter(state => state.name === 'Miranda')[0].id },
    { name: 'Maturín', stateId: states.filter(state => state.name === 'Monagas')[0].id },
    { name: 'Juan Griego', stateId: states.filter(state => state.name === 'Nueva Esparta')[0].id },
    { name: 'Pampatar', stateId: states.filter(state => state.name === 'Nueva Esparta')[0].id },
    { name: 'Porlamar', stateId: states.filter(state => state.name === 'Nueva Esparta')[0].id },
    { name: 'Acarigua', stateId: states.filter(state => state.name === 'Portuguesa')[0].id },
    { name: 'Acarigua-Anaure', stateId: states.filter(state => state.name === 'Portuguesa')[0].id },
    { name: 'Guanare', stateId: states.filter(state => state.name === 'Portuguesa')[0].id },
    { name: 'Turén', stateId: states.filter(state => state.name === 'Portuguesa')[0].id },
    { name: 'Carúpano', stateId: states.filter(state => state.name === 'Sucre')[0].id },
    { name: 'Casanay', stateId: states.filter(state => state.name === 'Sucre')[0].id },
    { name: 'Cumaná', stateId: states.filter(state => state.name === 'Sucre')[0].id },
    { name: 'San Antonio', stateId: states.filter(state => state.name === 'Táchira')[0].id },
    { name: 'San Cristóbal', stateId: states.filter(state => state.name === 'Táchira')[0].id },
    { name: 'Boconó', stateId: states.filter(state => state.name === 'Trujillo')[0].id },
    { name: 'La Puerta', stateId: states.filter(state => state.name === 'Trujillo')[0].id },
    { name: 'Sabana de Mendoza', stateId: states.filter(state => state.name === 'Trujillo')[0].id },
    { name: 'San Rafael de Carvajal', stateId: states.filter(state => state.name === 'Trujillo')[0].id },
    { name: 'Santa Isabel', stateId: states.filter(state => state.name === 'Trujillo')[0].id },
    { name: 'Trujillo', stateId: states.filter(state => state.name === 'Trujillo')[0].id },
    { name: 'Valera', stateId: states.filter(state => state.name === 'Trujillo')[0].id },    
    { name: 'Catia la Mar', stateId: states.filter(state => state.name === 'Vargas')[0].id },
    { name: 'La Guaira', stateId: states.filter(state => state.name === 'Vargas')[0].id },
    { name: 'Naiguatá', stateId: states.filter(state => state.name === 'Vargas')[0].id },
    { name: 'San Felipe', stateId: states.filter(state => state.name === 'Yaracuy')[0].id },
    { name: 'Yaritagua', stateId: states.filter(state => state.name === 'Yaracuy')[0].id },    
    { name: 'Cabimas', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Caja Seca', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Carrasquero', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Ciudad Ojeda', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'La Concepción', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Lagunillas', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Machiques', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Maracaibo', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Mene Grande', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Puertos de Altagracia', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'San Francisco Maracaibo', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'San Rafael del Moján', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Santa Bárbara del Zulia', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Santa Rita', stateId: states.filter(state => state.name === 'Zulia')[0].id },
    { name: 'Villa del Rosario', stateId: states.filter(state => state.name === 'Zulia')[0].id },
  ]

  module.exports = cities